language: generic
sudo: false
dist: trusty

notifications:
  email: false

addons:
  apt:
    sources:
    - sourceline: "deb http://archive.ubuntu.com/ubuntu/ xenial main universe"
    packages:
      - libgmp-dev=2:5.1.3+dfsg-1ubuntu1
      - libsdl2-dev=2.0.4+dfsg1-2ubuntu2
      - libsdl2-ttf-dev=2.0.14+dfsg1-1
      - libsdl2-gfx-dev=1.0.1+dfsg-3

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal build --only-dependencies

script:
  - stack --no-terminal build

cache:
  directories:
    - $HOME/.stack
