name:                lefrect
version:             0.1.0.0
github:              myuon/lefrect
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
copyright:           2018 myuon

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- Strict
- MultiWayIf

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/myuon/lefrect#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2
- sdl2-ttf
- sdl2-gfx
- linear
- mtl
- extensible
- lens

library:
  source-dirs: src

executables:
  lefrect-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lefrect

